services:
    app:
        env_file: !override
            - /home/rhaegal222/Server/system/ops/secrets/password-generator/production.env
        depends_on: !reset []
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        expose:
            - "80"

    db:
        profiles:
            - local-db
