services:
    db:
        environment:
            MYSQL_DATABASE: password_generator_000_staging
            MYSQL_ROOT_PASSWORD: password_generator_root
            MYSQL_USER: password_generator
            MYSQL_PASSWORD: password_generator_local

    app:
        environment:
            DB_HOST: db
            DB_DATABASE: password_generator_000_staging
            DB_USERNAME: password_generator
            DB_PASSWORD: password_generator_local
            DB_ROOT_PASSWORD: password_generator_root

    nginx:
        labels:
            - traefik.enable=false
