services:
    db:
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    app:
        volumes:
            - ./service:/var/www/html
            - /var/www/html/vendor

    nginx:
        volumes:
            - ./nginx/internal.conf:/etc/nginx/conf.d/default.conf:ro
            - ./service/public:/var/www/html/public:ro
        labels:
            - traefik.enable=false
